Develop graph
howard-university-web-services/hu_general pull request #6
Opened 2020-01-16 20:27 UTC by ben2collins

2020-01-16 20:29 UTC, ben2collins commented
@drogers98 Ran this stylesheet through the code cleaner.
Do you think it's ready to be merged into 8.x-1.x.

2020-01-22 15:02 UTC, drogers98 requested changes
adjust one spacing issue and will merge.

2020-01-22 15:02 UTC, drogers98 commented on idfive-component-library/src/components/ks/graph/graph.scss
> +        .hp_graph_bundle {
adjust indentation here please.

2020-01-22 15:29 UTC, ben2collins commented on idfive-component-library/src/components/ks/graph/graph.scss
> +        .hp_graph_bundle {
I followed your recommendation and  adjusted the stylesheet's indentation in my latest commit.

2020-01-22 15:38 UTC, merged